import { Images } from "./Images";

export const InterestList = [
  {
    title: "아웃도어/여행",
    interest: "outdoor",
    image: Images.outdoor,
    detail: [
      "등산",
      "산책/트래킹",
      "캠핑/백패킹",
      "국내여행",
      "해외여행",
      "낚시",
      "패러글라이딩",
    ],
  },
  {
    title: "운동/스포츠",
    interest: "sports",
    image: Images.sports,
    detail: [
      "자전거",
      "배드민턴",
      "볼링",
      "테니스/스쿼시",
      "스키/보드",
      "골프",
      "클라이밍",
      "다이어트",
      "헬스/크로스핏",
      "요가/필라테스",
      "탁구",
      "당구/포켓볼",
      "러닝/마라톤",
      "수영/스쿠버다이빙",
      "서핑/웨이크보드/요트",
      "축구/풋살",
      "농구",
      "야구",
      "배구",
      "승마",
      "펜싱",
      "복싱",
      "태권도/유도",
      "검도",
      "무술/주짓수",
      "스케이트/인라인",
      "크루즈보드",
      "족구",
      "양궁",
    ],
  },
  {
    title: "인문학/책/글",
    interest: "book",
    image: Images.book,
    detail: [
      "책/독서",
      "인문학",
      "심리학",
      "철학",
      "역사",
      "시사/경제",
      "작문/글쓰기",
    ],
  },
  {
    title: "외국/언어",
    interest: "language",
    image: Images.language,
    detail: ["영어", "일본어", "중국어", "프랑스어", "스페인어", "러시아어"],
  },
  {
    title: "문화/공연/축제",
    interest: "concert",
    image: Images.concert,
    detail: [
      "뮤지컬/오페라",
      "공연/연극",
      "영화",
      "전시회",
      "연기/공연제작",
      "고궁/문화재탐방",
      "파티/페스티벌",
    ],
  },
  {
    title: "음악/악기",
    interest: "music",
    image: Images.music,
    detail: [
      "노래/보컬",
      "기타/베이스",
      "우쿨렐레",
      "드럼",
      "피아노",
      "바이올린",
      "플룻",
      "오카리나",
      "밴드/합주",
      "작사/작곡",
      "인디음악",
      "랩/힙합/DJ",
      "클래식",
      "재즈",
      "락/메탈",
      "일렉트로닉",
      "국악/사물놀이",
      "찬양/CCM",
      "뉴에이지",
    ],
  },
  {
    title: "공예/만들기",
    interest: "craft",
    image: Images.craft,
    detail: [
      "미술/그림",
      "캘리그라피",
      "플라워아트",
      "캔들/디퓨저/석고",
      "천연비누/화장품",
      "소품공예",
      "가죽공예",
      "가구/목공예",
      "설탕/앙금공예",
      "도자/점토공예",
      "자수/뜨개질",
      "키덜트/프라모델",
      "메이크업/네일",
    ],
  },
  {
    title: "댄스/무용",
    interest: "dance",
    image: Images.dance,
    detail: [
      "라틴댄스",
      "사교댄스",
      "방송/힙합",
      "스트릿댄스",
      "발레",
      "재즈댄스",
      "한국무용",
      "밸리댄스",
      "현대무용",
      "스윙댄스",
    ],
  },
  {
    title: "봉사활동",
    interest: "volunteer",
    image: Images.volunteer,
    detail: [
      "양로원",
      "보육원",
      "환경봉사",
      "사회봉사",
      "교육/재능나눔",
      "유기동물보호",
    ],
  },
  {
    title: "사교/인맥",
    interest: "society",
    image: Images.society,
    detail: [
      "지역",
      "나이",
      "성별",
      "싱글/연애",
      "기혼/유부",
      "돌싱",
      "와인/커피/차",
      "맛집/미식회",
    ],
  },
  {
    title: "차/오토바이",
    interest: "car",
    image: Images.car,
    detail: [
      "현대",
      "기아",
      "르노",
      "GM",
      "쌍용",
      "일본차",
      "미국차",
      "유럽차",
      "바이크",
    ],
  },
  {
    title: "사진/영상",
    interest: "photo",
    image: Images.photo,
    detail: ["DSLR", "필름카메라", "영상제작", "디지털카메라"],
  },
  {
    title: "야구관람",
    interest: "baseball",
    image: Images.baseball,
    detail: [
      "삼성라이온즈",
      "기아타이거즈",
      "롯데자이언츠",
      "두산베어스",
      "LG트윈스",
      "SSG랜더스",
      "키움히어로즈",
      "한화이글스",
      "NC다이노스",
      "KT위즈",
    ],
  },
  {
    title: "게임/오락",
    interest: "game",
    image: Images.game,
    detail: [
      "다트",
      "보드게임",
      "두뇌심리게임",
      "온라인게임",
      "콘솔게임",
      "단체놀이",
      "타로카드",
      "마술",
      "바둑",
    ],
  },
  {
    title: "요리/제조",
    interest: "cook",
    image: Images.cook,
    detail: [
      "한식",
      "양식",
      "중식",
      "일식",
      "베이킹/제과",
      "핸드드립",
      "소믈리에/와인",
      "주류제조/칵테일",
    ],
  },
  {
    title: "반려동물",
    interest: "animal",
    image: Images.animal,
    detail: ["강아지", "고양이", "물고기", "파충류", "설치류/중치류"],
  },
  {
    title: "가족/결혼",
    interest: "family",
    image: Images.family,
    detail: ["결혼/웨딩", "육아/맘", "아빠/대디"],
  },
  {
    title: "자유주제",
    interest: "free",
    image: Images.free,
    detail: [
      "스피치/발성",
      "시험/자격증",
      "취업스터디",
      "금융보험",
      "기타(etc)",
    ],
  },
];
