import { Images } from "./Images";

export const testClubList = [
  {
    id: 1,
    clubTitle: "테스트",
    clubDescription: "테스트중입니다",
    interest: "outdoor",
    interestDetail: "",
    interestTitle: "아웃도어/여행",
    interestImage: Images.outdoor,
    clubImage: "http://placehold.it/100",
    region: "남구",
    city: "부산광역시",
    member: 1,
  },
  {
    id: 2,
    clubTitle: "테스트2",
    clubDescription: "테스트중입니다",
    interest: "game",
    interestDetail: "온라인게임",
    interestTitle: "게임/오락",
    interestImage: Images.game,
    clubImage: "http://placehold.it/100",
    region: "남구",
    city: "부산광역시",
    member: 3,
  },
  {
    id: 3,
    clubTitle: "테스트3",
    clubDescription: "테스트중입니다",
    interest: "car",
    interestDetail: "",
    interestTitle: "차/오토바이",
    interestImage: Images.car,
    clubImage: "http://placehold.it/100",
    region: "남구",
    city: "부산광역시",
    member: 5,
  },
  {
    id: 4,
    clubTitle: "테스트4",
    clubDescription: "테스트중입니다",
    interest: "game",
    interestDetail: "보드게임",
    interestTitle: "게임/오락",
    interestImage: Images.game,
    clubImage: "http://placehold.it/100",
    region: "남구",
    city: "서울특별시",
    member: 7,
  },
  {
    id: 5,
    clubTitle: "테스트5",
    clubDescription: "테스트중입니다",
    interest: "game",
    interestDetail: "보드게임",
    interestTitle: "게임/오락",
    interestImage: Images.game,
    clubImage: "http://placehold.it/100",
    region: "남구",
    city: "부산광역시",
    member: 7,
  },
  {
    id: 6,
    clubTitle: "테스트6",
    clubDescription: "테스트중입니다",
    interest: "game",
    interestDetail: "온라인게임",
    interestTitle: "게임/오락",
    interestImage: Images.game,
    clubImage: "http://placehold.it/100",
    region: "남구",
    city: "부산광역시",
    member: 9,
  },
  {
    id: 7,
    clubTitle: "마술 동호회7",
    clubDescription: "마술 동호회입니다",
    interest: "game",
    interestDetail: "마술",
    interestTitle: "게임/오락",
    interestImage: Images.game,
    clubImage: "http://placehold.it/100",
    region: "남구",
    city: "부산광역시",
    member: 13,
  },
  {
    id: 8,
    clubTitle: "마술 동호회8",
    clubDescription: "마술 동호회입니다",
    interest: "game",
    interestDetail: "마술",
    interestTitle: "게임/오락",
    interestImage: Images.game,
    clubImage: "http://placehold.it/100",
    region: "남구",
    city: "부산광역시",
    member: 13,
  },
  {
    id: 9,
    clubTitle: "마술 동호회9",
    clubDescription: "마술 동호회입니다",
    interest: "game",
    interestDetail: "마술",
    interestTitle: "게임/오락",
    interestImage: Images.game,
    clubImage: "http://placehold.it/100",
    region: "남구",
    city: "부산광역시",
    member: 13,
  },
  {
    id: 10,
    clubTitle: "마술 동호회10",
    clubDescription: "마술 동호회입니다",
    interest: "game",
    interestDetail: "마술",
    interestTitle: "게임/오락",
    interestImage: Images.game,
    clubImage: "http://placehold.it/100",
    region: "남구",
    city: "부산광역시",
    member: 13,
  },
  {
    id: 11,
    clubTitle: "마술 동호회11",
    clubDescription: "마술 동호회입니다",
    interest: "game",
    interestDetail: "마술",
    interestTitle: "게임/오락",
    interestImage: Images.game,
    clubImage: "http://placehold.it/100",
    region: "남구",
    city: "부산광역시",
    member: 13,
  },
  {
    id: 12,
    clubTitle: "마술 동호회12",
    clubDescription: "마술 동호회입니다",
    interest: "game",
    interestDetail: "마술",
    interestTitle: "게임/오락",
    interestImage: Images.game,
    clubImage: "http://placehold.it/100",
    region: "남구",
    city: "부산광역시",
    member: 13,
  },
];
